version: '3'
services:
  front-envoy:
    image: envoyproxy/envoy-alpine:v1.7.0
    volumes:
      - ./front/envoy.yaml:/etc/envoy-config.yaml
    ports:
      - "10000:10000"
      - "9901:9901"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --v2-config-only -l info --service-cluster 'front-envoy' --service-node 'front-envoy' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  service_a_envoy:
    image: envoyproxy/envoy-alpine:v1.7.0
    volumes:
      - ./service_a/envoy-config.yaml:/etc/envoy-config.yaml
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --v2-config-only -l info --service-cluster 'service-a' --service-node 'service-a' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  service_a:
    build: service_a/

  service_b_envoy:
    image: envoyproxy/envoy-alpine:v1.7.0
    volumes:
      - ./service_b/envoy-config.yaml:/etc/envoy-config.yaml
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --v2-config-only -l info --service-cluster 'service-a' --service-node 'service-a' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  service_b:
    build: service_b/

  service_b2:
    build: service_b2/
