version: '3'
services:
  front-envoy:
    image: envoyproxy/envoy-alpine-dev:latest
    volumes:
      - ./front/envoy.yaml:/etc/envoy-config.yaml
    ports:
      - "10000:10000"
      - "9901:9901"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --service-cluster 'front-envoy' --service-node 'front-envoy' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  service_a_envoy:
    image: envoyproxy/envoy-alpine-dev:latest
    volumes:
      - ./service_a/envoy-config.yaml:/etc/envoy-config.yaml
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --service-cluster 'service-a' --service-node 'service-a' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  service_a:
    build: service_a/

  service_b_envoy:
    image: envoyproxy/envoy-alpine-dev:latest
    volumes:
      - ./service_b/envoy-config.yaml:/etc/envoy-config.yaml
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --service-cluster 'service-b' --service-node 'service-b' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  service_b:
    build: service_b/

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 9411:9411
      - 16686:16686